### ISSUE TITLE
Tailwind theme extend removed

### ISSUE THREAD

**Issue by GreenDjango** [saadeghi/daisyui-demo#2]
> DaisyUI version: 0.15.0

Hi, the `colors.js` file for Tailwind theme don't exist any more.
It's a mistake or the doc it's just outdated ?
At https://daisy.js.org/docs/config:
```js
    // add DaisyUI colors (optional)
    theme: {
      extend: {
        colors: require('daisyui/colors'),
      },
    },
```

**Comment by saadeghi** [comment]
@GreenDjango Fixed (https://github.com/saadeghi/daisyui/commit/71fe7cb8dcedd16ac6379b4a68cb66a0a6e965d3)  
Please update to latest version (0.15.1)
